services:
  frontend:
    build:
      context: ./angular
    ports:
      - "3001:80"

  backend:
    build:
      context: ./nest
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
